# The docker-compose.yml file is __only__ used for local development.
# This means that changes to this file will not affect cloud deployments in any way.
# Read more at https://docs.divio.com/reference/docker-docker-compose/
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - "./data:/data:rw"
